package at.ac.fhcampuswien.models;

import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

// verifies the builder pattern on Movie.
class MovieBuilderTest {

    @Test
    void buildsMovieWithAllFields() {
        UUID id = UUID.randomUUID();

        Movie movie = Movie.builder()
                .id(id)
                .title("Inception")
                .genre("Sci-Fi")
                .releaseYear(2010)
                .build();

        assertEquals(id, movie.getId());
        assertEquals("Inception", movie.getTitle());
        assertEquals("Sci-Fi", movie.getGenre());
        assertEquals(2010, movie.getReleaseYear());
    }

    @Test
    void omittedIdGetsAutoGenerated() {
        Movie movie = Movie.builder()
                .title("Inception")
                .genre("Sci-Fi")
                .releaseYear(2010)
                .build();

        // the no-arg Movie constructor already assigns a random UUID; the
        // builder must preserve that behaviour when no explicit id is given.
        assertNotNull(movie.getId());
    }
}